### ISSUE TITLE
Document support for "URL as a source of metric data URLs"

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-integrations#21]
This is used in Spark and Couchbase integrations and may be used in other integrations in the future, so we should document how to do this.

**Comment by otisg** [comment]
Actually, @bsmid , do we have that new how-to linked from anywhere?  We should.

**Comment by bsmid** [comment]
We have, I linked to it from root sematext-agent-java README. You can see it in commit.

**Comment by otisg** [comment]
Yeah, just saw it.   Closing.

**Comment by otisg** [comment]
Btw. wouldn't it make more sense (for the developer/reader) to have that info in https://github.com/sematext/sematext-agent-java/blob/master/docs/metrics-yaml-format.md ?
Doesn't the bottom of this doc already have similar sections (grouping, processing, extracting...)?

I'm asking because having this knowledge about how to handle metrics for *integrations* linked to only from the *agent* README would make it easy for people to miss this info.
