### ISSUE TITLE
Add integration checks to help improve integrations

### ISSUE THREAD

**Issue by otisg** [sematext/sematext-agent-integrations#23]
We should add simple integration checks that help the integration author polish the integration.  Things like:

• "don't use /seconds, use /s"
• here is a list of all distinct units you used: requests/min, requests/minute....  ("oh, look, I used both /min and /minute, let me fix that"), millis, milliseconds ("oh, wait, I should unify these.  No, actually I should use ms, let me change that")
• here is a list of metrics with a missing label: ....
• here is a list of metrics with a missing description: ....

This will save time during PR reviews, help with unification across all integrations, let the PR reviewer focus on bigger, non-cosmetic things, etc.

**Comment by bsmid** [comment]
Hm, yeah, sorry about that.
