### ISSUE TITLE
Add support for /update handler in Request Rate & Latency graph for Solr

### ISSUE THREAD

**Issue by gr0** [sematext/sematext-agent-integrations#32]
We should have an out of the support for `/update` handler in the Request Rate & Latency graph for Solr, so that users can easily find out similar information about the rate and latency for requests sent to `/update` handler.

**Comment by otisg** [comment]
One can use https://github.com/sematext/sematext-agent-integrations/blob/master/solr/jmx-searcher-solr7plus.yml as a starting point.  Just map the JMX beans for /update handler.
